Fix admin login css 15
seport/SLLA pull request #28
Opened 2018-03-15 05:11 UTC by annaboeri

![screen shot 2018-03-14 at 10 09 15 pm](https://user-images.githubusercontent.com/32287328/37445304-83aa03ac-27d4-11e8-92ac-47e9015d4116.png)

2018-03-18 23:09 UTC, seport requested changes
Nice work! The only problem is that the formatting on the error message has been a little messed up now. Everything else looks good, though, so once this is fixed it should be good to merge! 👍Thanks so much!

<img width="556" alt="screen shot 2018-03-18 at 4 06 17 pm" src="https://user-images.githubusercontent.com/17886804/37572334-af65d22e-2ac6-11e8-8e43-cf2c2573c11b.png">

2018-03-20 04:25 UTC, annaboeri commented
I fixed the formatting on the error message. I wasn't quite sure what you wanted the error message to look like so if you wanted something different let me know and I can change it :)

2018-03-20 23:36 UTC, seport approved these changes

2018-03-20 23:39 UTC, seport commented
Thanks! I think there will be a ticket later to unify the CSS a bit more. For now this is good enough to merge! 👍You'll just need to rebase since some things have been merged. There will probably be a small merge conflict. If you need help walking through this process I can help with it tomorrow night. :)

2020-06-18 22:14 UTC, closed without merging